Patch 1
UI-Lovelace-Minimalist/UI pull request #1330
Opened 2023-07-10 20:02 UTC by M4rtik4

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: new translation
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [X] I have followed the [contribution guidelines](https://github.com/UI-Lovelace-Minimalist/UI/blob/main/.github/CONTRIBUTING.md)
    - [X] This PR is for a custom-card or documentation change and therefore directed to the `main` branch.
    - [ ] This PR is for a official card or any other directly to the integration related change and therefore directed to the `release` branch.

2023-07-10 20:06 UTC, Borty97 approved these changes

2023-07-10 22:17 UTC, Borty97 requested changes

2023-07-10 22:17 UTC, Borty97 commented on custom_components/ui_lovelace_minimalist/translations/ca.json
> +{
Correct translation. Good work!

2023-07-10 22:21 UTC, basbruss commented
New languages should also be added here to be picked up by the config flow.
https://github.com/UI-Lovelace-Minimalist/UI/blob/f9724d256130d1150469e41fe6a8db022705edf2/custom_components/ui_lovelace_minimalist/const.py#L21C1-L60C2

2023-07-11 17:13 UTC, Borty97 commented on custom_components/ui_lovelace_minimalist/translations/ca.json
> +            "github_cards": "Alguna cosa ha anat malament al obtenir tarjetes de GitHub.",
Change "tarjetes" for "targetes"

2023-07-12 19:36 UTC, M4rtik4 commented on custom_components/ui_lovelace_minimalist/translations/ca.json
> +            "github_cards": "Alguna cosa ha anat malament al obtenir tarjetes de GitHub.",
Done

2023-07-31 08:02 UTC, basbruss approved these changes

2023-07-31 08:02 UTC, merged