[custom_card_scenes]Option to trigger automation trigger
UI-Lovelace-Minimalist/UI pull request #833
Opened 2022-07-03 11:58 UTC by sildehoop

2022-07-03 12:03 UTC, mpeterson commented
@sildehoop you can discover the need to use the `automation.trigger` service by looking at the domain of the entity. That way you'll save yourself the variable.

2022-07-03 12:06 UTC, sildehoop commented
Oh nice i will do that.

2022-07-03 12:26 UTC, sildehoop commented
```yaml
```

2022-07-03 12:54 UTC, mpeterson commented
@sildehoop  https://github.com/UI-Lovelace-Minimalist/UI/blob/2f9e167c9ca8541dab63933553efb706c3324c3f/custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_card.yaml#L10

2022-07-04 17:53 UTC, mpeterson commented on custom_cards/custom_card_scenes/card_scenes.yaml
> +      automation: false
Don’t forget to remove the variables which are not needed anymore

2022-07-04 18:11 UTC, mpeterson requested changes

2022-07-04 18:11 UTC, mpeterson commented on custom_cards/custom_card_scenes/README.md
> +The `card_scenes` you can control up to 5 `entity` such as `scene` , `script` or `automation`.
Nit: you probably want to remove the space before the comma

2022-07-04 18:11 UTC, mpeterson commented on custom_cards/custom_card_scenes/card_scenes.yaml
> +            let domain = variables.entity_1.entity_id.substr(0, variables.entity_1.entity_id.indexOf("."));
In all blocks the let is not at the right indentation

2022-07-04 18:11 UTC, mpeterson commented on custom_cards/custom_card_scenes/card_scenes.yaml
> +            entity_id: "[[[ return variables.entity_1.entity_id ]]]"
Entity 5, right?

2022-07-04 18:16 UTC, sildehoop commented
You are very sharp😉

2022-07-04 18:36 UTC, mpeterson approved these changes
LGTM

2022-07-05 06:32 UTC, basbruss approved these changes

2022-07-05 06:33 UTC, merged